version: '3.8'

services:
  api:
    image: apicred:latest  # Sua nova imagem da API
    container_name: api_container
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bdcompras
      SPRING_DATASOURCE_USERNAME: jasp
      SPRING_DATASOURCE_PASSWORD: 0101
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - rede-app

  db:
    image: postgres:latest
    ports:
      - "5433:5432" # Mapeando a porta 5432 do container para a 5433 do host
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: bdcompras
      POSTGRES_USER: jasp
      POSTGRES_PASSWORD: 0101  # 🔥 Adicionando senha obrigatória!
    networks:
      - rede-app

networks:
  rede-app:
    driver: bridge