version: '3.8'

services:
  api:
    image: meuusuario/minha-api:latest  # Substitua pela sua imagem da API
    container_name: api_container
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bdcompras
      SPRING_DATASOURCE_USERNAME: jasp
      SPRING_DATASOURCE_PASSWORD: 0101
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - rede-app

  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: bdcompras
      POSTGRES_USER: jasp
      POSTGRES_PASSWORD: 0101
    networks:
      - rede-app

networks:
  rede-app:
    driver: bridge